### ISSUE TITLE
Password "paste" disabled

### ISSUE THREAD

**Issue by brianmgray** [Dinius/Brain.fm-Desktop-Client#11]
Paste is disabled when entering password into the desktop client. There is also no option to make the password visible. Both of these make it difficult to use password management tools like LastPass. 

After entering my password incorrectly a handful of times, I had to change my password online to something simple to type, enter it into the desktop client, then change it back to my generated LastPass password.

Is there a reason paste is disabled? If not, please re-enable it? I gather this is a client-specific setting as I can paste into the brain.fm website.

**Comment by Dinius** [comment]
This should work in the newest version. See https://github.com/Dinius/Brain.fm-Desktop-Client/issues/8
For the record, it was never intentionally *disabled*, but OSX requires you to have some menus in place to enable pasting otherwise the paste command is just ignored/unavailable (I'm not an OSX user so I never noticed).
