### ISSUE TITLE
Logout doesn't work correctly

### ISSUE THREAD

**Issue by RonanCodes** [Dinius/Brain.fm-Desktop-Client#12]
When you click log out it doesn't bring you to the login screen, it doesn't navigate anywhere new in fact.
If I click log out again it states that I do not have access to this screen.

Closing the app and reopening brings you back to the login screen.

**Comment by Dinius** [comment]
Tested now with 0.1.5 and it works for me on both macos and windows. 

Does this happen every time for you? And with the newest version? 

Sounds like there's some script error occurring on the "Brain.fm side" *(what happens "in the app" in that sense isn't in my control as such, because it actually happens on Brain.fm's website).* But if I could reproduce it I could probably make a fix to work around it.

**Comment by RonanCodes** [comment]
It doesn't seem to be happening anymore.
I'm on MacOS High Sierra: 10.13.4
